import { Router, Request, Response } from "express";

const router = Router();

router.post("/commit", async (req: Request, res: Response) => {
  try {
    console.log(req.body);
    return res.status(200).send(req.body);
  } catch (error) {}
});

router.post("/pr", async (req: Request, res: Response) => {
  try {
    //req.body.pull_request.title
    console.log(req.body);
    return res.status(200).send(req.body);
  } catch (error) {}
});

export default router;

let x ={
    action: 'closed',
    number: 3,
    pull_request: {
      url: 'https://api.github.com/repos/yashrajillusion/linear-server/pulls/3',
      id: 1263342340,
      number: 3,
      state: 'closed',
      locked: false,
      title: 'created patch request for status updation',
      user: {
        login: 'yash-chace',
        id: 108513845,
        node_id: 'U_kgDOBnfKNQ',
        avatar_url: 'https://avatars.githubusercontent.com/u/108513845?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/yash-chace',
        html_url: 'https://github.com/yash-chace',
        followers_url: 'https://api.github.com/users/yash-chace/followers',
        following_url: 'https://api.github.com/users/yash-chace/following{/other_user}',
        gists_url: 'https://api.github.com/users/yash-chace/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/yash-chace/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/yash-chace/subscriptions',
        organizations_url: 'https://api.github.com/users/yash-chace/orgs',
        repos_url: 'https://api.github.com/users/yash-chace/repos',
        events_url: 'https://api.github.com/users/yash-chace/events{/privacy}',
        received_events_url: 'https://api.github.com/users/yash-chace/received_events',
        type: 'User',
        site_admin: false
      },
      body: 'Pr for patch request',
      created_at: '2023-03-05T09:07:07Z',
      updated_at: '2023-03-05T09:26:14Z',
      closed_at: '2023-03-05T09:26:13Z',
      merged_at: '2023-03-05T09:26:13Z',
      merge_commit_sha: 'c7f83f026fc0152860d34b8d9f5e20e75f8280ac',
      assignee: null,
      assignees: [],
      requested_reviewers: [],
      requested_teams: [],
      labels: [],
      milestone: null,
      draft: false,
      commits_url: 'https://api.github.com/repos/yashrajillusion/linear-server/pulls/3/commits',
      review_comments_url: 'https://api.github.com/repos/yashrajillusion/linear-server/pulls/3/comments',
      review_comment_url: 'https://api.github.com/repos/yashrajillusion/linear-server/pulls/comments{/number}',
      comments_url: 'https://api.github.com/repos/yashrajillusion/linear-server/issues/3/comments',
      statuses_url: 'https://api.github.com/repos/yashrajillusion/linear-server/statuses/986f08a543725524fd33aaed30f0b9863c814af1',
      head: {
        label: 'yashrajillusion:create_patch_request',
        ref: 'create_patch_request',
        sha: '986f08a543725524fd33aaed30f0b9863c814af1',
        user: [Object],
        repo: [Object]
      },
      base: {
        label: 'yashrajillusion:main',
        ref: 'main',
        sha: 'c5b05cb28ddec20eeae0a88efbe58e1f8de2f16f',
        user: [Object],
        repo: [Object]
      },
      _links: {
        self: [Object],
        html: [Object],
        issue: [Object],
        comments: [Object],
        review_comments: [Object],
        review_comment: [Object],
        commits: [Object],
        statuses: [Object]
      },
      author_association: 'COLLABORATOR',
      auto_merge: null,
      active_lock_reason: null,
      merged: true,
      mergeable: null,
      rebaseable: null,
      mergeable_state: 'unknown',
      merged_by: {
        login: 'yashrajillusion',
        id: 95868808,
        node_id: 'U_kgDOBbbXiA',
        avatar_url: 'https://avatars.githubusercontent.com/u/95868808?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/yashrajillusion',
        html_url: 'https://github.com/yashrajillusion',
        followers_url: 'https://api.github.com/users/yashrajillusion/followers',
        following_url: 'https://api.github.com/users/yashrajillusion/following{/other_user}',
        gists_url: 'https://api.github.com/users/yashrajillusion/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/yashrajillusion/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/yashrajillusion/subscriptions',
        organizations_url: 'https://api.github.com/users/yashrajillusion/orgs',
        repos_url: 'https://api.github.com/users/yashrajillusion/repos',
        events_url: 'https://api.github.com/users/yashrajillusion/events{/privacy}',
        received_events_url: 'https://api.github.com/users/yashrajillusion/received_events',
        type: 'User',
        site_admin: false
      },
      comments: 0,
      review_comments: 0,
      maintainer_can_modify: false,
      commits: 2,
      additions: 38,
      deletions: 1,
      changed_files: 3
    },
    repository: {
      id: 606826978,
      node_id: 'R_kgDOJCtx4g',
      name: 'linear-server',
      full_name: 'yashrajillusion/linear-server',
      private: false,
      owner: {
        login: 'yashrajillusion',
        id: 95868808,
        node_id: 'U_kgDOBbbXiA',
        avatar_url: 'https://avatars.githubusercontent.com/u/95868808?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/yashrajillusion',
        html_url: 'https://github.com/yashrajillusion',
        followers_url: 'https://api.github.com/users/yashrajillusion/followers',
        following_url: 'https://api.github.com/users/yashrajillusion/following{/other_user}',
        gists_url: 'https://api.github.com/users/yashrajillusion/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/yashrajillusion/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/yashrajillusion/subscriptions',
        organizations_url: 'https://api.github.com/users/yashrajillusion/orgs',
        repos_url: 'https://api.github.com/users/yashrajillusion/repos',
        events_url: 'https://api.github.com/users/yashrajillusion/events{/privacy}',
        received_events_url: 'https://api.github.com/users/yashrajillusion/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/yashrajillusion/linear-server',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/yashrajillusion/linear-server',
      forks_url: 'https://api.github.com/repos/yashrajillusion/linear-server/forks',
      keys_url: 'https://api.github.com/repos/yashrajillusion/linear-server/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/yashrajillusion/linear-server/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/yashrajillusion/linear-server/teams',
      hooks_url: 'https://api.github.com/repos/yashrajillusion/linear-server/hooks',
      issue_events_url: 'https://api.github.com/repos/yashrajillusion/linear-server/issues/events{/number}',
      events_url: 'https://api.github.com/repos/yashrajillusion/linear-server/events',
      assignees_url: 'https://api.github.com/repos/yashrajillusion/linear-server/assignees{/user}',
      branches_url: 'https://api.github.com/repos/yashrajillusion/linear-server/branches{/branch}',
      tags_url: 'https://api.github.com/repos/yashrajillusion/linear-server/tags',
      blobs_url: 'https://api.github.com/repos/yashrajillusion/linear-server/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/yashrajillusion/linear-server/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/yashrajillusion/linear-server/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/yashrajillusion/linear-server/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/yashrajillusion/linear-server/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/yashrajillusion/linear-server/languages',
      stargazers_url: 'https://api.github.com/repos/yashrajillusion/linear-server/stargazers',
      contributors_url: 'https://api.github.com/repos/yashrajillusion/linear-server/contributors',
      subscribers_url: 'https://api.github.com/repos/yashrajillusion/linear-server/subscribers',
      subscription_url: 'https://api.github.com/repos/yashrajillusion/linear-server/subscription',
      commits_url: 'https://api.github.com/repos/yashrajillusion/linear-server/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/yashrajillusion/linear-server/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/yashrajillusion/linear-server/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/yashrajillusion/linear-server/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/yashrajillusion/linear-server/contents/{+path}',
      compare_url: 'https://api.github.com/repos/yashrajillusion/linear-server/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/yashrajillusion/linear-server/merges',
      archive_url: 'https://api.github.com/repos/yashrajillusion/linear-server/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/yashrajillusion/linear-server/downloads',
      issues_url: 'https://api.github.com/repos/yashrajillusion/linear-server/issues{/number}',
      pulls_url: 'https://api.github.com/repos/yashrajillusion/linear-server/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/yashrajillusion/linear-server/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/yashrajillusion/linear-server/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/yashrajillusion/linear-server/labels{/name}',
      releases_url: 'https://api.github.com/repos/yashrajillusion/linear-server/releases{/id}',
      deployments_url: 'https://api.github.com/repos/yashrajillusion/linear-server/deployments',
      created_at: '2023-02-26T17:25:05Z',
      updated_at: '2023-02-27T19:03:38Z',
      pushed_at: '2023-03-05T09:26:13Z',
      git_url: 'git://github.com/yashrajillusion/linear-server.git',
      ssh_url: 'git@github.com:yashrajillusion/linear-server.git',
      clone_url: 'https://github.com/yashrajillusion/linear-server.git',
      svn_url: 'https://github.com/yashrajillusion/linear-server',
      homepage: null,
      size: 5,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main'
    },
  }
                